name: better_player_example
description: Better Player example usage app.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  #better_player: any
  better_player:
    path: package/better_player
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.0.1
  visibility_detector: ^0.2.0-nullsafety.1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/
  uses-material-design: true