name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.0.63
authors:
  - Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/betterplayer

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  wakelock: ^0.4.0
  pedantic: ^1.11.0
  meta: ^1.3.0
  flutter_widget_from_html_core: ^0.6.0-rc.2021030201
  visibility_detector: ^0.2.0-nullsafety.1
  path_provider: ^2.0.1
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1
  flutter_localizations:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: FLTBetterPlayerPlugin
